# -----------------------------------------------------------------------------
# Shared platform Cloud SQL for Postgres instance + the plant-log database.
#
# Per docs/stack-devops.md: ONE Postgres instance for the platform; each product
# gets a separate database on it until load argues otherwise. This PR is where
# that shared instance is born (plant-log is the first deploy). Future product
# databases attach here rather than creating new instances.
#
# Stateful resource → prevent_destroy = true AND deletion_protection = true.
# A plan that shows this instance being destroyed must stop the task.
# -----------------------------------------------------------------------------

resource "google_sql_database_instance" "platform" {
  name             = var.sql_instance_name
  database_version = "POSTGRES_16"
  region           = var.region

  # API-level guard: refuses `terraform destroy` / console deletion.
  deletion_protection = true

  settings {
    tier              = var.db_tier
    availability_type = "ZONAL"
    disk_autoresize   = true

    # The Cloud SQL API now defaults new POSTGRES_16 instances to ENTERPRISE_PLUS,
    # which rejects shared-core tiers like db-f1-micro. We want the cheap Enterprise
    # edition (db-f1-micro is a supported shared-core tier there; PITR is supported).
    # Pinning this explicitly also insulates us from a future API default change.
    edition = "ENTERPRISE"

    backup_configuration {
      enabled                        = true
      point_in_time_recovery_enabled = true
    }

    ip_configuration {
      # Public IP, but NO authorized_networks: every Cloud SQL instance must
      # enable at least one connectivity method (Public IP, Private IP, or PSC),
      # so a public IP is enabled to satisfy that API requirement. With zero
      # authorized_networks, no arbitrary host on the internet can reach the
      # instance directly. The only path in is the Cloud SQL Auth Proxy that
      # Cloud Run mounts as a socket: it authenticates via IAM (the runtime SA
      # holds roles/cloudsql.client) and tunnels over TLS. This is the standard
      # Cloud Run -> Cloud SQL pattern. Private IP (VPC + Serverless VPC
      # connector) is deliberately not used here; deferred.
      ipv4_enabled = true

      # Defense in depth: reject any unencrypted connection. ENCRYPTED_ONLY
      # mandates TLS without requiring client certificates (the Auth Proxy
      # already establishes TLS, so this does not break the Cloud Run socket).
      ssl_mode = "ENCRYPTED_ONLY"
    }
  }

  # State-store safety: Terraform must never plan a destroy of this instance.
  lifecycle {
    prevent_destroy = true
  }
}

# The product database. Alembic (run at container start) manages its schema.
resource "google_sql_database" "plantlog" {
  name     = "plantlog"
  instance = google_sql_database_instance.platform.name
}

# Least-privilege application user for plant-log. Its password is generated by
# Terraform (below) and never chosen by a human or committed anywhere.
#
# NOTE on grants: BUILT_IN Cloud SQL users are members of cloudsqlsuperuser.
# True per-table least privilege is enforced with SQL GRANTs, which are managed
# by the app's migrations, not here. Scoping this user to the `plantlog`
# database is the practical boundary at the infra layer. See Follow-ups.
resource "google_sql_user" "plantlog" {
  name     = "plantlog"
  instance = google_sql_database_instance.platform.name
  password = random_password.plantlog_db.result
}

# 32-char URL-safe password (only -/_ specials so it needs no URL-encoding when
# embedded in the DATABASE_URL connection string).
resource "random_password" "plantlog_db" {
  length           = 32
  special          = true
  override_special = "-_"
}
