# -----------------------------------------------------------------------------
# Shared platform Cloud SQL for Postgres instance + the plant-log database.
#
# Per docs/stack-devops.md: ONE Postgres instance for the platform; each product
# gets a separate database on it until load argues otherwise. This PR is where
# that shared instance is born (plant-log is the first deploy). Future product
# databases attach here rather than creating new instances.
#
# Stateful resource → prevent_destroy = true AND deletion_protection = true.
# A plan that shows this instance being destroyed must stop the task.
# -----------------------------------------------------------------------------

resource "google_sql_database_instance" "platform" {
  name             = var.sql_instance_name
  database_version = "POSTGRES_16"
  region           = var.region

  # API-level guard: refuses `terraform destroy` / console deletion.
  deletion_protection = true

  settings {
    tier              = var.db_tier
    availability_type = "ZONAL"
    disk_autoresize   = true

    backup_configuration {
      enabled                        = true
      point_in_time_recovery_enabled = true
    }

    ip_configuration {
      # No public IP and no authorized networks: the instance is reached only
      # through the Cloud SQL connector socket that Cloud Run mounts. It is not
      # exposed to the internet.
      ipv4_enabled = false
      # Private IP would require a VPC + Serverless VPC connector; deferred.
      # With ipv4_enabled=false and no private network, connectivity is via the
      # Cloud SQL Auth proxy/connector only (how Cloud Run's socket works).
    }
  }

  # State-store safety: Terraform must never plan a destroy of this instance.
  lifecycle {
    prevent_destroy = true
  }
}

# The product database. Alembic (run at container start) manages its schema.
resource "google_sql_database" "plantlog" {
  name     = "plantlog"
  instance = google_sql_database_instance.platform.name
}

# Least-privilege application user for plant-log. Its password is generated by
# Terraform (below) and never chosen by a human or committed anywhere.
#
# NOTE on grants: BUILT_IN Cloud SQL users are members of cloudsqlsuperuser.
# True per-table least privilege is enforced with SQL GRANTs, which are managed
# by the app's migrations, not here. Scoping this user to the `plantlog`
# database is the practical boundary at the infra layer. See Follow-ups.
resource "google_sql_user" "plantlog" {
  name     = "plantlog"
  instance = google_sql_database_instance.platform.name
  password = random_password.plantlog_db.result
}

# 32-char URL-safe password (only -/_ specials so it needs no URL-encoding when
# embedded in the DATABASE_URL connection string).
resource "random_password" "plantlog_db" {
  length           = 32
  special          = true
  override_special = "-_"
}
