# -----------------------------------------------------------------------------
# Inputs. Every deployment-specific value arrives here; nothing is hard-coded.
# Values with no default are REQUIRED and must be supplied in terraform.tfvars
# (see terraform.tfvars.example). No secret value is ever a variable — secrets
# are generated by Terraform (random) or set out-of-band in Secret Manager.
# -----------------------------------------------------------------------------

variable "project_id" {
  description = "GCP project ID that hosts the platform (created day zero, by hand)."
  type        = string
}

variable "region" {
  description = "Default GCP region for regional resources (Cloud Run, Artifact Registry, Cloud SQL)."
  type        = string
  default     = "us-central1"
}

# --- Shared platform Cloud SQL instance ---------------------------------------

variable "sql_instance_name" {
  description = "Name of the shared platform Cloud SQL for Postgres instance. Product databases live as separate databases on this one instance (per docs/stack-devops.md)."
  type        = string
  default     = "platform-pg"
}

variable "db_tier" {
  description = "Cloud SQL machine tier for the shared instance. db-f1-micro is fine for the current single-product load; bump when load argues otherwise."
  type        = string
  default     = "db-f1-micro"
}

# --- plant-log service --------------------------------------------------------

variable "artifact_registry_repo" {
  description = "Artifact Registry Docker repository ID for plant-log images."
  type        = string
  default     = "plant-log"
}

variable "plantlog_image" {
  description = <<-EOT
    Fully-qualified container image for the plant-log Cloud Run service. Defaults
    to a public placeholder so the very first `apply` can stand up the service
    before any real image exists in Artifact Registry (chicken-and-egg on day
    zero). The real image is delivered afterward by `gcloud run deploy` or the CI
    deploy workflow (follow-up); Terraform ignores subsequent image changes so it
    never reverts a shipped revision.
  EOT
  type        = string
  default     = "us-docker.pkg.dev/cloudrun/container/hello"
}

variable "allowed_emails" {
  description = "Comma-separated allow-list of the two household Google accounts permitted to sign in. Not a secret (email addresses), passed as a plain env var."
  type        = string
}

variable "google_client_id" {
  description = "Google OAuth 2.0 Web client ID for sign-in. Not a secret; passed as a plain env var. The matching client *secret* is stored in Secret Manager, set out-of-band."
  type        = string
  default     = ""
}

variable "google_redirect_uri" {
  description = "OAuth redirect URI. Depends on the final Cloud Run URL / custom domain, which is unknown until the service exists — set it after the first deploy and re-apply. May be blank on the first apply."
  type        = string
  default     = ""
}

# --- team-higgs command center (day-zero address bridge) ----------------------

variable "higgs_command_image" {
  description = <<-EOT
    Fully-qualified container image for the higgs-command Cloud Run placeholder.
    A disposable default (the public Cloud Run hello image) whose only job is to
    hold the higgs.tylerdorland.com mapping and warm the managed cert. The real
    command center is a SEPARATE, gated service (its own project/identity/auth) —
    NOT this one — so no real image is ever delivered here; this placeholder is
    retired at cutover. `ignore_changes` on the image only keeps Terraform from
    reverting an out-of-band swap of this holding page.
  EOT
  type        = string
  default     = "us-docker.pkg.dev/cloudrun/container/hello"
}
