# -----------------------------------------------------------------------------
# Inputs. Every deployment-specific value arrives here; nothing is hard-coded.
# Values with no default are REQUIRED and must be supplied in terraform.tfvars
# (see terraform.tfvars.example). No secret value is ever a variable — secrets
# are generated by Terraform (random) or set out-of-band in Secret Manager.
# -----------------------------------------------------------------------------

variable "project_id" {
  description = "GCP project ID that hosts the platform (created day zero, by hand)."
  type        = string
}

variable "region" {
  description = "Default GCP region for regional resources (Cloud Run, Artifact Registry, Cloud SQL)."
  type        = string
  default     = "us-central1"
}

# --- Shared platform Cloud SQL instance ---------------------------------------

variable "sql_instance_name" {
  description = "Name of the shared platform Cloud SQL for Postgres instance. Product databases live as separate databases on this one instance (per docs/stack-devops.md)."
  type        = string
  default     = "platform-pg"
}

variable "db_tier" {
  description = "Cloud SQL machine tier for the shared instance. db-f1-micro is fine for the current single-product load; bump when load argues otherwise."
  type        = string
  default     = "db-f1-micro"
}

# --- plant-log service --------------------------------------------------------

variable "artifact_registry_repo" {
  description = "Artifact Registry Docker repository ID for plant-log images."
  type        = string
  default     = "plant-log"
}

variable "plantlog_image" {
  description = <<-EOT
    Fully-qualified container image for the plant-log Cloud Run service. Defaults
    to a public placeholder so the very first `apply` can stand up the service
    before any real image exists in Artifact Registry (chicken-and-egg on day
    zero). The real image is delivered afterward by `gcloud run deploy` or the CI
    deploy workflow (follow-up); Terraform ignores subsequent image changes so it
    never reverts a shipped revision.
  EOT
  type        = string
  default     = "us-docker.pkg.dev/cloudrun/container/hello"
}

variable "allowed_emails" {
  description = "Comma-separated allow-list of the two household Google accounts permitted to sign in. Not a secret (email addresses), passed as a plain env var."
  type        = string
}

variable "google_client_id" {
  description = "Google OAuth 2.0 Web client ID for sign-in. Not a secret; passed as a plain env var. The matching client *secret* is stored in Secret Manager, set out-of-band."
  type        = string
  default     = ""
}

variable "google_redirect_uri" {
  description = "OAuth redirect URI. Depends on the final Cloud Run URL / custom domain, which is unknown until the service exists — set it after the first deploy and re-apply. May be blank on the first apply."
  type        = string
  default     = ""
}

variable "canonical_host" {
  description = "Apex canonical host for the www->apex 301 (plant-log). Empty disables the redirect (local/CI/.run.app). Set to the apex domain in tfvars at cutover."
  type        = string
  default     = ""
}

# --- team-higgs command center (day-zero address bridge) ----------------------

variable "higgs_command_image" {
  description = <<-EOT
    Fully-qualified container image for the higgs-command Cloud Run placeholder.
    A disposable default (the public Cloud Run hello image) whose only job is to
    hold the higgs.tylerdorland.com mapping and warm the managed cert. The real
    command center is a SEPARATE, gated service (its own project/identity/auth) —
    NOT this one — so no real image is ever delivered here; this placeholder is
    retired at cutover. `ignore_changes` on the image only keeps Terraform from
    reverting an out-of-band swap of this holding page.
  EOT
  type        = string
  default     = "us-docker.pkg.dev/cloudrun/container/hello"
}

# --- command center (the REAL gated service; command_center.tf) ---------------

variable "enable_command_center" {
  description = <<-EOT
    Master switch for the gated command-center service (command_center.tf). When
    false (the default), EVERY command_center.tf resource is count=0 — the service,
    its runtime SA, its four secrets, and their IAM are not created. This keeps the
    apply-on-merge pipeline unblocked while the command center is still pre-launch:
    its resources are NOT in Terraform state, so gating to 0 is a true no-op (zero
    destroys). It is flipped to true by the reachability epic (task #33), together
    with a real cc_google_client_id, when the IAP-fronted load balancer that makes
    the service reachable lands. Until then it must stay false in CI.
  EOT
  type        = bool
  default     = false
}

variable "command_center_image" {
  description = <<-EOT
    Fully-qualified container image for the command-center Cloud Run service.
    Defaults to the public hello image so the first apply can stand the service
    up before a real image exists in Artifact Registry (day-zero chicken-and-egg,
    same as plant-log). The real image is shipped afterward by `gcloud run deploy`
    or a CI deploy workflow (follow-up); `ignore_changes` on the image keeps
    Terraform from reverting a shipped revision.
  EOT
  type        = string
  default     = "us-docker.pkg.dev/cloudrun/container/hello"
}

variable "cc_allowed_emails" {
  description = "Allow-list for the command center — Tyler only (decision #17). Not a secret (an email address); passed as a plain env var."
  type        = string
  default     = "tyler@tylerdorland.com"
}

variable "cc_google_client_id" {
  description = <<-EOT
    Google OAuth 2.0 Web client ID for the command-center sign-in. NOT a secret
    (the matching client *secret* lives in Secret Manager). A non-empty value both
    wires real OIDC and arms the backend's fail-closed DEV_AUTH guard
    (command_center/config.py), so a blank must never ship WITH THE SERVICE LIVE.
    This is a NEW OAuth client, separate from plant-log's — Tyler creates it and
    supplies the ID in terraform.tfvars when enable_command_center flips to true.

    Default is "" so that, while the service is gated OFF (enable_command_center =
    false), no value is demanded and the apply-on-merge plan resolves from
    ci.auto.tfvars alone. The fail-closed intent is preserved by the validation
    below: an empty ID is rejected the moment the service is enabled.
  EOT
  type        = string
  default     = ""

  validation {
    # Fail closed: the command center must never be stood up with a blank
    # GOOGLE_CLIENT_ID. The empty default is valid ONLY while enable_command_center
    # is false (the resources are count=0); enabling the service demands a real ID.
    condition     = !var.enable_command_center || length(trimspace(var.cc_google_client_id)) > 0
    error_message = "cc_google_client_id must be a non-empty OAuth client ID when enable_command_center = true (it arms the fail-closed DEV_AUTH guard, command_center/config.py). Set it in terraform.tfvars / ci.auto.tfvars, or set enable_command_center = false."
  }
}

variable "cc_google_redirect_uri" {
  description = "OAuth redirect URI for the command center. Defaults to the higgs.tylerdorland.com callback; must be added as an Authorized redirect URI on the OAuth client."
  type        = string
  default     = "https://higgs.tylerdorland.com/api/auth/callback"
}
